package ru.rmatyuk.calculationtaxbot.enums

enum class ConfigType {
    RATE_TOTAL_PRICE_JPY,
    IMPERIAL_TAX_PERCENT1,
    IMPERIAL_TAX_PERCENT2,
    DELIVERY_JPY,
    AUCTION_FEE_JPY1,
    AUCTION_FEE_JPY2,
    AGENT_COMMISSION_JPY1,
    AGENT_COMMISSION_JPY2,
    IMPORT_CONTINENT_RUB1,
    IMPORT_CONTINENT_RUB2,
    FREIGHT_USD1,
    FREIGHT_USD2,
    BANKING_FEES_PERCENT,
    SVH_RUB,
    PRICE_ONE_HORSE,
    COUNT_HORSE_WITH_CALCULATE,
    DELIVERY_RUS,
    MARGIN_PERCENT,
    MIN_MARGIN

}